let pokemonJson = [
    { id: 2, name: 'Ivysaur', cod: '#0002', img: 'src/img/ivysaur.gif', primeiro_tipo: 'Grama', segundo_tipo: 'Veneno', descricao: 'Quando o bulbo nas costas cresce, parece perder a capacidade de ficar de pé nas patas traseiras.' },
    { id: 3, name: 'Venusaur', cod: '#0003', img: 'src/img/venusaur.gif', primeiro_tipo: 'Grama', segundo_tipo: 'Veneno', descricao: 'Sua planta floresce quando está absorvendo energia solar. Ele permanece em movimento para buscar a luz do sol.' },
    { id: 4, name: 'Charmander', cod: '#0004', img: 'src/img/charmander.gif', primeiro_tipo: 'Fogo', segundo_tipo: '🔥', descricao: 'Ele tem preferencia por coisas quentes. Quando chove, diz-se que o vapor jorra da ponta de sua cauda.' },
    { id: 5, name: 'Charmeleon', cod: '#0005', img: 'src/img/charmeleon.gif', primeiro_tipo: 'Fogo', segundo_tipo: '🔥', descricao: 'Tem uma natureza bárbara. Em batalha, ele chicoteia sua cauda de fogo e corta com garras afiadas.' },
    { id: 6, name: 'Charizard', cod: '#0006', img: 'src/img/charizard.gif', primeiro_tipo: 'Fogo', segundo_tipo: 'Ar', descricao: 'Ele cospe fogo que é quente o suficiente para derreter pedras. Pode causar incêndios florestais soprando chamas.' },
    { id: 7, name: 'Squirtle', cod: '#0007', img: 'src/img/squirtle.gif', primeiro_tipo: 'Agua', segundo_tipo: '💦', descricao: 'Quando retrai seu longo pescoço em sua concha, esguicha água com força vigorosa.' },
    { id: 8, name: 'Wartortle', cod: '#0008', img: 'src/img/wartortle.gif', primeiro_tipo: 'Agua', segundo_tipo: '💦', descricao: 'É reconhecido como um símbolo de longevidade. Se sua casca tiver algas, aquele Wartortle é muito velho.' },
    { id: 9, name: 'Blastoise', cod: '#0009', img: 'src/img/blastoise.gif', primeiro_tipo: 'Agua', segundo_tipo: '💦', descricao: 'Ele esmaga seu inimigo sob seu corpo pesado para causar desmaios. Em uma pitada, ele se retirará para dentro de sua casca.' },
    { id: 10, name: 'Caterpie', cod: '#0010', img: 'src/img/caterpie.gif', primeiro_tipo: 'Bug', segundo_tipo: '🌬️', descricao: 'Para proteção, ele libera um fedor horrível da antena em sua cabeça para afastar os inimigos.' }
]